### ISSUE TITLE
Add support for symlinks

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm-emms#11]
helm-emms skips symlinks in `helm-source-emms-dired`.
This may be the desired behaviour for some users, but not all.

In particular, there are two typical scenarios:

- `emms-source-file-default-directory` is a symlink.  I personally like to have `~/music` symlinked to my storage drive.

The following patch could be enough:

```diff
                  (helm-walk-directory
-                   emms-source-file-default-directory
+                   (file-truename emms-source-file-default-directory)
                   :directories 'only
                   :path 'full)
```

- Symlinks are found inside `emms-source-file-default-directory`.  I understand it could be desirable to not follow symlinks (mostly to avoid circular links) but some people may like it.
What about adding an option?

```diff
(cl-defun helm-walk-directory (directory &key (path 'basename)
; ...
-                  (unless (file-symlink-p dir)
+                  (unless (or helm-emms-skip-symlinks (file-symlink-p dir))

```

Thoughts?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> helm-emms skips symlinks in helm-source-emms-dired.
> This may be the desired behaviour for some users, but not all.
>
> In particular, there are two typical scenarios:
>
>   * emms-source-file-default-directory is a symlink. I personally like to have ~/music symlinked to my storage drive.

What about 
(setq emms-source-file-default-directory (file-truename "/your/symlink")) ?

>   * Symlinks are found inside emms-source-file-default-directory. I understand it could be desirable to not follow symlinks (mostly to avoid circular links)
>     but some people may like it.
>     What about adding an option?
>
> (cl-defun helm-walk-directory (directory &key (path 'basename)
> ; ...
> -                  (unless (file-symlink-p dir)
> +                  (unless (or helm-emms-skip-symlinks (file-symlink-p dir))
>
> Thoughts?

No, helm-walk-directory is too slow to support such option (in addition
of inconvenients you mentioned above). And of course an helm-emms var
should not be used inside a generalized helm function like
helm-walk-directory, instead an option (e.g. :follow-symlinks) should be added.

-- 
Thierry

**Comment by Ambrevar** [comment]
> What about 
> (setq emms-source-file-default-directory (file-truename "/your/symlink")) ?

But I won't be the only one to be tripped by this, so it would be nice if
Helm-EMMS would just do the right thing for every user.  It comes at no cost
after all :)

> No, helm-walk-directory is too slow to support such option (in addition
> of inconvenients you mentioned above).

Fair enough :)

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

>> What about
>> (setq emms-source-file-default-directory (file-truename "/your/symlink")) ?
>
> But I won't be the only one to be tripped by this, so it would be nice if
> Helm-EMMS would just do the right thing for every user. It comes at no cost
> after all :)

Yes that can be done, but not through helm-walk-directory, just with
something like

    (setq emms-source-file-default-directory (file-truename emms-source-file-default-directory))

-- 
Thierry

**Comment by Ambrevar** [comment]
Maybe you misunderstood: I'm not saying we should modify `helm-walk-directory` but `helm-source-emms-dired` as in the first patch I posted.

I understand it's a nit... :)

**Comment by Ambrevar** [comment]
Thanks for the fix.
