### ISSUE TITLE
helm-emms can't display chinese.

### ISSUE THREAD

**Issue by dingyi342** [emacs-helm/helm-emms#20]
![deepin-screenshot3770807599](https://user-images.githubusercontent.com/36829022/60385667-3844af80-9abe-11e9-8553-4924ea99ec2f.png)

helm-find-file display chinese correctly.
![deepin-screenshot3770807653](https://user-images.githubusercontent.com/36829022/60385669-3d096380-9abe-11e9-88a0-76a68b3d0cd2.png)

**Comment by thierryvolpiatto** [comment]
Is EMMS (without helm) displaying file names properly?

**Comment by dingyi342** [comment]
> Is EMMS (without helm) displaying file names properly?

Yes. I only find font promblem in helm-emms.
![deepin-screenshot3770811622](https://user-images.githubusercontent.com/36829022/60386472-b8234780-9ac7-11e9-86f5-ff02e754a101.png)

**Comment by thierryvolpiatto** [comment]
dingyi342 <notifications@github.com> writes:

>     Is EMMS (without helm) displaying file names properly?
>    
> Yes. I only find font promblem in helm-emms.
> deepin-s

Can you eval this and show me result:

    (cl-loop for v being the hash-values in emms-cache-db
             for name      = (assoc-default 'name v)
             for artist    = (or (assoc-default 'info-artist v) "unknown")
             for genre     = (or (assoc-default 'info-genre v) "unknown")
             for tracknum  = (or (assoc-default 'info-tracknumber v) "unknown")
             for song      = (or (assoc-default 'info-title v) "unknown")
             for info      = (if helm-emms-use-track-description-function
                                 (funcall emms-track-description-function v)
                               (concat artist " - " genre " - " tracknum ": " song))
             unless (string-match "^\\(http\\|mms\\):" name)
             collect (cons info name))

Thanks.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by dingyi342** [comment]
![deepin-screenshot3770839424](https://user-images.githubusercontent.com/36829022/60390384-18d27480-9b08-11e9-81b8-527d89a02c7d.png)

**Comment by dingyi342** [comment]
Is it a format problem with my music file naming?

**Comment by dingyi342** [comment]
EMMS can't read the music file name to display the music name and singer.
EMMS read from music file tags, and I don't set the tag of the music file, so EMMS can't display it.
