### ISSUE TITLE
emms-helm shows "unknown" for all untagged files

### ISSUE THREAD

**Issue by jave** [emacs-helm/helm-emms#3]
I had a directory where files were untagged.

All files are shown as "unknown" by emms-helm

**Comment by thierryvolpiatto** [comment]
Could you make a recipe so that I can reproduce ?
Also can you reproduce after rebuilding the emms cache ?

**Comment by thierryvolpiatto** [comment]
Looks like a problem not related to helm, you have to tag your files with an external tool like easy-tag.
