### ISSUE TITLE
Error invoking helm-emms

### ISSUE THREAD

**Issue by K0HAX** [emacs-helm/helm-emms#4]
`M-x helm-emms` produces the following error.
`apply: Symbol's function definition is void: helm-adaptive-sort`

This occurs on a fresh reinstall of helm and helm-emms.

**Comment by wigust** [comment]
Hello @K0HAX,

I got this issue, too.  To resolve it you need `(require 'helm-adaptive)` in your **.emacs**.

I wonder should it be mentioned in the **README**?

**Comment by thierryvolpiatto** [comment]
Fixed, sorry for late reply @K0HAX I haven't been notified of your issue by mail.

**Comment by wigust** [comment]
Hello @thierryvolpiatto,

Thanks, it works with 8133c1a854c8f9e32b3b4c74638fe197535c08f1.  I guess you could close the issue.

**Comment by Ambrevar** [comment]
@thierryvolpiatto: Not closing?

**Comment by thierryvolpiatto** [comment]
Just forgot closing this, doing now.
