### ISSUE TITLE
Fail gracefully when emms-source-file-default-directory is nil

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm-emms#5]
At the moment, `helm-emms` will fail if emms-source-file-default-directory is nil:

```
Wrong type argument: stringp, nil
```

I believe `helm-emms` should catch this error and warn the user.
If the cache is non-empty, then `helm-emms` can proceed with that source anyways.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I believe helm-emms should catch this error and warn the user.
> If the cache is non-empty, then helm-emms can proceed with that source anyways.

Done, thanks.

-- 
Thierry
