### ISSUE TITLE
Searching and displaying albums according to artist

### ISSUE THREAD

**Issue by easyunko** [emacs-helm/helm-emms#6]
I'm using emms-print-metadata to display my info. I noticed in your picture that you've got all the album info, artist, genre, album name displayed in the buffer, but that isn't true for me, regardless of whether helm-use-track-description-function is toggled. I search for Ambitious Lovers, and you get a bunch of tracks by them but not full albums. You can search by album, but there's no artist name. If there's no thumbnail, helm-emms displays the path to the album directory.

That probably wasn't too clear, so here's an image that illustrates what I'm talking about: https://i.imgur.com/dCXGU7m.gif

**Comment by thierryvolpiatto** [comment]
easyunko <notifications@github.com> writes:

> I'm using emms-print-metadata to display my info. I noticed in your
> picture that you've got all the album info, artist, genre, album name
> displayed in the buffer, but that isn't true for me, regardless of
> whether helm-use-track-description-function is toggled.

It is helm-emms-use-track-description-function.

> I search for Ambitious Lovers, and you get a bunch of tracks by them
> but not full albums. You can search by album, but there's no artist
> name.

This is all about tagging your album files, which is sometimes tricky,
you can try using https://wiki.gnome.org/Apps/EasyTAG or id3v2 on
command line (perhaps with a script), there is also many other
applications for tagging.

> If there's no thumbnail, helm-emms displays the path to the album
> directory.

You have to create a default cover

    (setq emms-browser-default-covers '("~/.emacs.d/emms/cover_small.jpg"))

--
Thierry

**Comment by thierryvolpiatto** [comment]
![capture d ecran_2018-01-31_06-14-32](https://user-images.githubusercontent.com/1533939/35606213-1323ce30-064e-11e8-914b-1b90ef61ba6b.png)

**Comment by thierryvolpiatto** [comment]
According to your gif, your album should be something like:

<image> Ambitious lover - <year> - Lust

instead of just Lust.

**Comment by easyunko** [comment]
> It is helm-emms-use-track-description-function.
I've toggled it both ways. Doesn't really change anything other than displaying the genre.
> This is all about tagging your album files, which is sometimes tricky, you can try using https://wiki.gnome.org/Apps/EasyTAG or id3v2 on command line (perhaps with a script), there is also many other applications for tagging.
I don't know why that would be an issue, since the track descriptions demonstrated that the metadata was already properly written.

**Comment by thierryvolpiatto** [comment]
easyunko <notifications@github.com> writes:

> I don't know why that would be an issue, since the track
> descriptions demonstrated that the metadata was already properly
> written.

It is simple, if your album title is "Lust" and doesn't contain the artist
name "Ambitious Lovers" you will not be able to match the artist name.

Perhaps you missed the comment on the github web interface, have a look.

Thanks.

-- 
Thierry

**Comment by easyunko** [comment]
Ah, I see what you mean. Sorry for the hassle.
