### ISSUE TITLE
Music directory: Support multiple candidates

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm-emms#7]
Currently selecting multiple candidates in the "Music Directory" source has no effect.
It would be convenient if it would add/play all the selected candidates.

By the way, I suggest renaming "Music Directory" to "Music directories".

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Currently selecting multiple candidates in the "Music Directory" source has no effect.
> It would be convenient if it would add/play all the selected candidates.

Done.

> By the way, I suggest renaming "Music Directory" to "Music directories".

Done.

Thanks.

-- 
Thierry

**Comment by Ambrevar** [comment]
Thanks!
